version: '3.3'

services:
  mariadb:
    image: mariadb:latest
    container_name: MARIADB
    hostname: local_mariadb
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_picpay
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: APP
    volumes:
      - ./:/var/www/html
    restart: on-failure
    ports:
      - 80:80
      - 13000:13000
    depends_on:
      - mariadb
      - redis
    networks:
      - app
  
  redis:
    image: redis
    container_name: REDIS
    restart: always
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'

networks:
  app:
    driver: bridge